name: nearby_connections_example
description: Demonstrates how to use the nearby_connections plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  image_picker: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2

  nearby_connections:
    path: ../

flutter:


  uses-material-design: true
